FROM elvisnw/gradle-8.0-milestone-3-bin AS build
COPY . /home/app/
WORKDIR /home/app/services/discovery-server/
RUN gradle build

FROM openjdk:19-jdk-alpine
WORKDIR /usr/app
COPY --from=build /home/app/services/discovery-server/build/libs/*.jar /usr/app/app.jar
ENTRYPOINT ["java","-jar","/usr/app/app.jar"]